# Generated by Django 4.2.3 on 2023-07-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_price_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='gallery'),
        ),
    ]
